version: "3.8"
services:
  react:
    build: ./front/
    image: react_img
    container_name: react
    #environment:
    #  - PORT=4200
    ports:
      - 4200:4200
    #command: ["tail", "-f", "/dev/null"]
    #.PROD-MODE--
    #command: sh -c "cd /usr/src/app && npm run preview"
    #.DEV-MODE--
    #command: sh -c "cd /usr/src/app && npm run dev"
    volumes:
      - ./front:/usr/src/app
    #.-----

  express:
    build: ./back/
    image: express_img
    container_name: express
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 3000:3000
    #command: ["tail", "-f", "/dev/null"]
    #.PROD-MODE--
    #command: sh -c "cd /usr/src/app && "
    #.DEV-MODE--
    #command: sh -c "cd /usr/src/app && "
    volumes:
      - ./back:/usr/src/app
    #.-----
  
  postgres:
    #On utilise postgis pour pouvoir utiliser les fonctionalite liees a la geolocalisation
    image: postgis/postgis:latest
    container_name: postgres
    hostname: postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports: 
      - 3500:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U userpg -d db"]
      interval: 20s
      timeout: 5s
      retries: 5

volumes:
  db_data: